### ISSUE TITLE
Is possible to test user defined inputs and highest matched sentence

### ISSUE THREAD

**Issue by yogesh-0586** [zhiguowang/BiMPM#12]
I'm curious about this code is possible to check user defined sentence and matched closed match sentence like retrieval based chat bot . In my use case I want to train my model with some questions and check against user defined question to find out closest match question.

**Comment by zhiguowang** [comment]
It will work. We have the corresponding experiments in Section 4.5 of our paper https://arxiv.org/pdf/1702.03814.pdf
