### ISSUE TITLE
Error when parsing the test set

### ISSUE THREAD

**Issue by hadilnc01** [zhiguowang/BiMPM#14]
Hello,

The model was finally done with training on the dev set but when it was about to start with the test set, it gave a really big error:

> Validation Data Eval:
> Current accuracy is 87.35
> Best accuracy on dev set is 87.35
> Decoding on the test set:
> WARNING:tensorflow:From SentenceMatchTrainer.py:330 in main.: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
> Instructions for updating:
> Please use tf.global_variables instead.
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> Traceback (most recent call last):
>   File "SentenceMatchTrainer.py", line 391, in <module>
>     tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
>   File "/Users/dc-hadil/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
>     sys.exit(main(sys.argv[:1] + flags_passthrough))
>   File "SentenceMatchTrainer.py", line 339, in main
>     saver.restore(sess, best_path)
>   File "/Users/dc-hadil/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1388, in restore
>     {self.saver_def.filename_tensor_name: save_path})
>   File "/Users/dc-hadil/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
>     run_metadata_ptr)
>   File "/Users/dc-hadil/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 964, in _run
>     feed_dict_string, options, run_metadata)
>   File "/Users/dc-hadil/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
>     target_list, options, run_metadata)
>   File "/Users/dc-hadil/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> 	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
> 
> Caused by op u'save/RestoreV2', defined at:
>   File "SentenceMatchTrainer.py", line 391, in <module>
>     tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
>   File "/Users/dc-hadil/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
>     sys.exit(main(sys.argv[:1] + flags_passthrough))
>   File "SentenceMatchTrainer.py", line 334, in main
>     saver = tf.train.Saver(vars_)
>   File "/Users/dc-hadil/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1000, in __init__
>     self.build()
>   File "/Users/dc-hadil/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1030, in build
>     restore_sequentially=self._restore_sequentially)
>   File "/Users/dc-hadil/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 624, in build
>     restore_sequentially, reshape)
>   File "/Users/dc-hadil/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 361, in _AddRestoreOps
>     tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
>   File "/Users/dc-hadil/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 200, in restore_op
>     [spec.tensor.dtype])[0])
>   File "/Users/dc-hadil/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 441, in restore_v2
>     dtypes=dtypes, name=name)
>   File "/Users/dc-hadil/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
>     op_def=op_def)
>   File "/Users/dc-hadil/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
>     original_op=self._default_original_op, op_def=op_def)
>   File "/Users/dc-hadil/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
>     self._traceback = _extract_stack()
> 
> NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for models//SentenceMatch.sample.best.model
> 	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Is there a way to pick up the process from the test set? or do I have to start with the training all over again? Also, why was there an error?

**Comment by zhiguowang** [comment]
You can fix this problem easily by modifying the path from "models//SentenceMatch.sample.best.model" to "models/SentenceMatch.sample.best.model".

(Just replace the double slash into a single slash)

The new version fo tensorflow doesn't support double slash in the path.

**Comment by hadilnc01** [comment]
Ok I ran the command you shared and I was able to get results but I didn't understand the output. I thought I would get a 0 or 1 output in the case of "prediction" and a probability in the case of "probs". Can you please explain to me the output so I can make sense of it?

In the case of "prediction" I got the below sample:
> 0	0	hh	what is hh ?
> 0	1	what me worry ?	what is worrying ?
> 1	0	where is armenia ?	what is armenia ?
> 0	0	what is e-hrm ?	what is hrm ?
> 1	1	is/was quora down ?	was quora down ?

**What is the difference between the values in the first column and the second? Which one is the prediction?**

In the case of "probs" I got the below sample:
> 0	1:0.182387366891 0:0.817612707615
> 0	1:0.663396537304 0:0.336603462696
> 1	1:0.211678221822 0:0.788321793079
> 0	1:0.00674327090383 0:0.993256688118
> 1	1:0.86587280035 0:0.134127125144

**I thought that the one with the highest probability would be put in the first column but that's not the case. If you look at the second row, it has a label 0 (in the first column) even though the label 1 has a higher probability.**

Apologies for the constant questions but I don't want to assume wrong information :/

**Comment by zhiguowang** [comment]
For the "prediction" file, the first column is the ground-truth, and the second column is the predictions.
You can refer to https://github.com/zhiguowang/BiMPM/blob/master/src/SentenceMatchTrainer.py#L93

For the "probs" file, the first column is the ground-truth, and the following items are the probs for all possible labels.
You can refer to https://github.com/zhiguowang/BiMPM/blob/master/src/SentenceMatchTrainer.py#L98

**Comment by hadilnc01** [comment]
Ok great! Thank you very much for the explanation! 👍
