### ISSUE TITLE
Testing on unlabelled data

### ISSUE THREAD

**Issue by hadilnc01** [zhiguowang/BiMPM#15]
Now that I have the model trained and ready, how can I let it predict the labels of unlabelled questions?

In your instructions, you say that the test and trainings sets need to be in the following format:
> label sentence#1 sentence#2 other_info

But if I want to run the model on unlabelled data, then I won't know the value of "label". How can I build my file and have the trained model predict the labels? I would have put dummy values for "label" but I'm worried it might affect the model's performance later on. Or is that not the case?

**Comment by zhiguowang** [comment]
Just put dummy values. I will not affect anything.

**Comment by hadilnc01** [comment]
👍
