### ISSUE TITLE
why not saving word_embedding when you are training it?

### ISSUE THREAD

**Issue by rajarsheem** [zhiguowang/BiMPM#19]
I noticed that you are updating the word embedding while training.
Then why you are not saving it . Because of not saving it, when I restore the model, it gets randomly initialized and thus gives random results.

**Comment by zhiguowang** [comment]
My default setting (the "--fix_word_vec" in the command line) will not update the word embeddings. https://github.com/zhiguowang/BiMPM/blob/master/src/SentenceMatchModelGraph.py#L30

**Comment by rajarsheem** [comment]
Yeah but the not-saving-of-embedding setting is not conditional. It doesn't save the embedding irrespective of what ```fix_word_vec``` is.

**Comment by zhiguowang** [comment]
Yes. You are right.
You can add the condition at here https://github.com/zhiguowang/BiMPM/blob/master/src/SentenceMatchTrainer.py#L236

**Comment by zhiguowang** [comment]
And here https://github.com/zhiguowang/BiMPM/blob/master/src/SentenceMatchDecoder.py#L113
