### ISSUE TITLE
Speed factor of the Model?

### ISSUE THREAD

**Issue by uduse** [zhiguowang/BiMPM#22]
What are the factors that affects the evaluation speed of the model significantly without improving the performance much? in other words, what parameter to adjust to make the model evaluates faster without sacrificing too much accuracy? figuring this out by trials and errors is too time consuming, and any comment or suggestion is welcomed. Thank you!

**Comment by xljhtq** [comment]
Do you know the answer above?  I also want to know the reason. If not , do you have tried many other ways ? Please tell me , Thanks!

**Comment by uduse** [comment]
Closed due to inactivity.
