### ISSUE TITLE
Word Vector Path

### ISSUE THREAD

**Issue by hadilnc01** [zhiguowang/BiMPM#9]
Can someone please tell me what the Word Vector (i.e. the input for the --word_vec_path flag) file should contain? I read through the paper but I didn't find any useful indications.

**Comment by zhiguowang** [comment]
Here is the dataset used in the paper https://drive.google.com/file/d/0B0PlTAo--BnaQWlsZl9FZ3l1c28/view
You can have a look at the wordvec file

**Comment by hadilnc01** [comment]
Thank you! I'm glad the readme.txt file included in your zip lead me to where I can get more information about the word vectors!
